### ISSUE TITLE
Upload Manta MTA to server

### ISSUE THREAD

**Issue by mikeOwn** [sydhad/setUp#2]
Необходимо загрузить на сервер Амазона мейл агент для отправки почты Manta MTA
1. Скачиваем софт http://manta.io/;
2. Загружаем на сервер Амазона;
3. Настраиваем доступа на manta.ourDomain.com как тут: https://github.com/sydhad/setUp/issues/3
4. Готовим доступы для haduigon и mikeOwn к админ панели.

**Comment by haduigon** [comment]
То же самое делаем и с Mautic?

Assigned #2 https://github.com/sydhad/setUp/issues/2 to @haduigon
https://github.com/haduigon.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
https://github.com/sydhad/setUp/issues/2#event-711880302, or mute the
thread
https://github.com/notifications/unsubscribe/ATVq5VDElXpzvn9-fLGXbNXZGzyW8r9oks5qSOETgaJpZM4JEP4G
.

**Comment by mikeOwn** [comment]
Да, потом одну к другой присоединяем, настраиваем пару виртаульных серверов, проверяем, чтобы пуляло почту через настроенные на маутике кампаниях и двигаемся дальше -_-

Задача по Маутику ось: https://github.com/sydhad/setUp/issues/1

**Comment by haduigon** [comment]
Сколько всего виртуальных серверов надо ?
04 июл 2016 г. 13:36 пользователь "mikeOwn" notifications@github.com
написал:

**Comment by mikeOwn** [comment]
2 хватит с головой. потому что 1 - это как лох, а вот больше чем 2 и не надо пока что.

**Comment by haduigon** [comment]
И два сервера на амазоне, окей
04 июл 2016 г. 13:41 пользователь "mikeOwn" notifications@github.com
написал:

**Comment by mikeOwn** [comment]
а зачем на амазоне два сервера? -_-

**Comment by haduigon** [comment]
Ну два виртуальных сервера
04 июл 2016 г. 13:43 пользователь "mikeOwn" notifications@github.com
написал:

**Comment by mikeOwn** [comment]
Только для виртуальных серверов для отправки почты надо использовать вот такие инстансы: http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/elastic-ip-addresses-eip.html

**Comment by mikeOwn** [comment]
Откладывается.
